pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }

 stage('Database') {
      agent {
        docker { image 'openjdk:17-jdk-slim' }
      }
      steps {
            sh 'java Helloworld'
      }
    }


     stage('Database') {
      agent {
        docker { image 'mysql:8.0' }
      }
      steps {
        sh 'mysql --version'
      }
    }

    
  }
}
